### ISSUE TITLE
运行报错 [TUN] Start tun retrying lookup default interface after failure because system just booted

### ISSUE THREAD

**Issue by LittleRey** [d2184/clash#1]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 dev 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

最新

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
# port: 7890
# socks-port: 7891
# redir-port: 7892
mixed-port: 7890

# Port of MITM proxy server on the local end
mitm-port: 7894
allow-lan: true
bind-address: '*'
mode: rule
log-level: debug
external-controller: :9090
secret: ''
ipv6: false
external-ui: Dashboard

# geodata-mode: true 
# tcp-concurrent: true 
# enable-process: true


########################################### redir-host ###########################################
hosts:
#   '*.clash.dev': 127.0.0.1
#   '.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'
#MyDomain
#   '+.workers.dev': 162.159.36.1
#   '+.buildtest.site': 162.159.36.1
   'blog.buildtest.site': 162.159.36.1
   'googledrive.buildtest.site': 162.159.36.1
   'node.buildtest.site': 162.159.36.1
   'proxy.buildtest.site': 162.159.36.1
   'cproxy.buildtest.site': 162.159.36.1
#   'google.ns.buildtest.site': 162.159.36.1
#   'cloudflare.ns.buildtest.site': 162.159.36.1
#   'adguard.ns.buildtest.site': 162.159.36.1
#DNS Stamps
   'dns.alidns.com': 223.5.5.5
   'dns.tuna.tsinghua.edu.cn': 101.6.6.6
   'ipv4-zepto-sel-1.edge.nextdns.io': 103.127.124.46
   'ipv4-starry-osa-1.edge.nextdns.io': 203.76.245.200
   'ipv4-anexia-han-1.edge.nextdns.io': 203.162.172.59
   'ipv4-xtom-osa-1.edge.nextdns.io': 103.88.47.112
   'ipv4-greencloud-han-1.edge.nextdns.io': 103.199.17.192
   'ipv4-anexia-tpe-1.edge.nextdns.io': 37.252.243.39
   'ipv4-vultr-sel-1.edge.nextdns.io': 141.164.63.208
   'ipv4-imcloud-tpe-1.edge.nextdns.io': 103.246.218.132
   'ipv4-zepto-hkg-1.edge.nextdns.io': 45.11.104.186
   'ipv4-anexia-hkg-1.edge.nextdns.io': 37.252.249.233

############################################## DNS ##############################################
dns:
  enable: true
  ipv6: false
  listen: :53
  use-hosts: true
#  nameserver-policy:
#    'localhost.ptlogin2.qq.com': '223.5.5.5'
#    'dns.msftncsi.com': '223.5.5.5'
#    'www.msftncsi.com': '223.5.5.5'
#    'www.msftconnecttest.com': '223.5.5.5'
#    'post.buildtest.site': '223.5.5.5'
#    'stormnettestv3ray.herokuapp.com': '223.5.5.5'

  enhanced-mode: fake-ip
############################################ fake ip ############################################
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: 
    - '*.lan'
    - '*.local'
    - 'stun.*.*.*'
    - 'stun.*.*'
    - 'localhost.ptlogin2.qq.com'
    - '*.msftncsi.com'
    - '*.msftconnecttest.com'

  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
    - 162.159.36.5

  nameserver-policy:
#    'localhost.ptlogin2.qq.com': '223.5.5.5'
#    '+.internal.crop.com': '223.5.5.5'
#    '+.msftncsi.com': '223.5.5.5'
#    '+.msftconnecttest.com': '223.5.5.5'
#    'post.buildtest.site': '223.5.5.5'
#    'stormnettestv3ray.herokuapp.com': '223.5.5.5'

#PUBG
    '+.pubgha.com': 'https://120.53.53.53/dns-query'
    '+.kraftonde.com': 'https://120.53.53.53/dns-query'
    '+.playbattlegrounds.com': 'https://120.53.53.53/dns-query'
    '+.playbattlegrounds.com.cn': 'https://120.53.53.53/dns-query'
    '+.pubgbluehole.com': 'https://120.53.53.53/dns-query'
    '+.vivox.com': 'https://120.53.53.53/dns-query'

#CDN
    '+.amazonaws.com': 'https://120.53.53.53/dns-query'
    '+.amazonaws.com.cn': 'https://120.53.53.53/dns-query'
    '+.aliyuncs.com': 'https://223.5.5.5/dns-query'

  nameserver:
#dns from dhcp
#    - dhcp://en0
#    - dhcp://WLAN
#    - dhcp://wlan

#iqiq.io(Filter ?/log ?)
#    - quic://b.iqiq.io:784
#    - quic://h.iqiq.io:784
#    - quic://j.iqiq.io:784
#    - quic://c.passcloud.xyz:784
#    - quic://x.passcloud.xyz:784
#    - tls://b.iqiq.io:853
#    - tls://h.iqiq.io:853
#    - tls://j.iqiq.io:853
#    - tls://c.passcloud.xyz:853
#    - tls://x.passcloud.xyz:853

#Tencent DnsPod(Filtering/loging/Warning!)
    - tls://120.53.53.53:853
    - tls://1.12.12.12:853
    - https://120.53.53.53/dns-query
    - https://1.12.12.12/dns-query

#AliDNS(Filtering/loging/Edns/Warning!)
    - tls://dns.alidns.com:853
    - https://dns.alidns.com/dns-query

#Cfiec DNS(Filtering/loging/Warning!)
    - tls://dns.ipv6dns.com:853
    - https://dns.ipv6dns.com/dns-query

#Tuna DNS(Filter ?/log ?/Edns)
    - tls://dns.tuna.tsinghua.edu.cn:8853
    - https://dns.tuna.tsinghua.edu.cn:8443/dns-query

  fallback: 
#    - 'tls://8.8.4.4:853#DNSg'       #【Meta专属】"#DNSg"代表该DNS服务器通过
                                     # 名为"DNSg"的proxy Group访问
#UN-CN Dot NO 853(Filter ?/log ?)
#    - tls://dns.cmrg.net:53053
#    - tls://dns.cmrg.net:443

#Cloudflare Doh(No Filter/No log/Anycast/Edns)
#    - quic://1.1.1.1:784
    - tls://1.1.1.1:853
    - https://1.1.1.1/dns-query

    - 'tls://1.0.0.1:853#故障转移'
    - 'https://1.0.0.1/dns-query#故障转移'

#    - https://162.159.36.1/dns-query
#    - https://162.159.46.1/dns-query
  #119.29.29.29
  #    - https://119dot29dot29dot29.cloudflare-dns.com/dns-query

#Google Doh(No Filter/loging/Anycast/Edns)
#    - quic://8.8.8.8:784
    - tls://8.8.8.8:853
    - https://8.8.8.8/dns-query

    - 'tls://8.8.4.4:853#故障转移'
    - 'https://8.8.4.4/dns-query#故障转移'

#IBM Doh(No Filter/No log/Anycast/Edns)
    - 'tls://9.9.9.10:853#故障转移'
    - 'tls://149.112.112.10:853#故障转移'
    - 'https://9.9.9.10:5053/dns-query#故障转移'
    - 'https://149.112.112.10:5053/dns-query#故障转移'
    - 'https://9.9.9.10/dns-query#故障转移'
    - 'https://149.112.112.10/dns-query#故障转移'

    - tls://9.9.9.12:853
    - tls://149.112.112.12:853
    - https://9.9.9.12:5053/dns-query
    - https://149.112.112.12:5053/dns-query
    - https://9.9.9.12/dns-query
    - https://149.112.112.12/dns-query

#Adguard(No Filter/No log/Anycast)
#    - quic://94.140.14.140:784
    - tls://94.140.14.140:853
    - https://94.140.14.140/dns-query

#    - 'quic://94.140.14.141:784#故障转移'
    - 'tls://94.140.14.141:853#故障转移'
    - 'https://94.140.14.141/dns-query#故障转移'

#Uncensoreddns(No Filter/No log/Anycast/Uncensored DNS Server)
#    - tls://anycast.uncensoreddns.org:853
#    - https://anycast.uncensoreddns.org/dns-query
#    - tls://91.239.100.100:853
#    - https://91.239.100.100/dns-query

#Nextdns(No Filter/No log/Anycast)
#    - quic://ipv4-zepto-sel-1.edge.nextdns.io:853
#    - quic://ipv4-starry-osa-1.edge.nextdns.io:853
#    - quic://ipv4-anexia-han-1.edge.nextdns.io:853
#    - quic://ipv4-xtom-osa-1.edge.nextdns.io:853
#    - quic://ipv4-greencloud-han-1.edge.nextdns.io:853
#    - quic://ipv4-anexia-tpe-1.edge.nextdns.io:853
#    - quic://ipv4-vultr-sel-1.edge.nextdns.io:853
#    - quic://ipv4-imcloud-tpe-1.edge.nextdns.io:853
#    - quic://ipv4-zepto-hkg-1.edge.nextdns.io:853
#    - quic://ipv4-anexia-hkg-1.edge.nextdns.io:853

    - tls://ipv4-zepto-sel-1.edge.nextdns.io:853
    - tls://ipv4-starry-osa-1.edge.nextdns.io:853
    - tls://ipv4-anexia-han-1.edge.nextdns.io:853
    - tls://ipv4-xtom-osa-1.edge.nextdns.io:853
    - tls://ipv4-greencloud-han-1.edge.nextdns.io:853
    - tls://ipv4-anexia-tpe-1.edge.nextdns.io:853
    - tls://ipv4-vultr-sel-1.edge.nextdns.io:853
    - tls://ipv4-imcloud-tpe-1.edge.nextdns.io:853
    - tls://ipv4-zepto-hkg-1.edge.nextdns.io:853
    - tls://ipv4-anexia-hkg-1.edge.nextdns.io:853

    - tls://ipv4-dns1.nextdns.io:853
    - tls://ipv4-dns2.nextdns.io:853
    - tls://ipv4-anycast.dns1.nextdns.io:853
    - tls://ipv4-anycast.dns2.nextdns.io:853


    - https://ipv4-zepto-sel-1.edge.nextdns.io/dns-query
    - https://ipv4-starry-osa-1.edge.nextdns.io/dns-query
    - https://ipv4-anexia-han-1.edge.nextdns.io/dns-query
    - https://ipv4-xtom-osa-1.edge.nextdns.io/dns-query
    - https://ipv4-greencloud-han-1.edge.nextdns.io/dns-query
    - https://ipv4-anexia-tpe-1.edge.nextdns.io/dns-query
    - https://ipv4-vultr-sel-1.edge.nextdns.io/dns-query
    - https://ipv4-imcloud-tpe-1.edge.nextdns.io/dns-query
    - https://ipv4-zepto-hkg-1.edge.nextdns.io/dns-query
    - https://ipv4-anexia-hkg-1.edge.nextdns.io/dns-query
    - https://ipv4-dns1.nextdns.io/dns-query
    - https://ipv4-dns2.nextdns.io/dns-query
    - https://ipv4-anycast.dns1.nextdns.io/dns-query
    - https://ipv4-anycast.dns2.nextdns.io/dns-query


#    - tls://ipv6-anexia-tpe-1.edge.nextdns.io:853
#    - tls://ipv6-vultr-sel-1.edge.nextdns.io:853
#    - tls://ipv6-anexia-hkg-1.edge.nextdns.io:853
#    - tls://ipv6-vultr-sin-1.edge.nextdns.io:853
#    - tls://ipv6-starry-osa-1.edge.nextdns.io:853
#    - tls://ipv6-xtom-osa-1.edge.nextdns.io:853
#    - tls://ipv6-zepto-hkg-1.edge.nextdns.io:853
#    - tls://ipv6-greencloud-han-1.edge.nextdns.io:853
#    - tls://ipv6-dns1.nextdns.io:853
#    - tls://ipv6-dns2.nextdns.io:853
#    - https://ipv6-anexia-tpe-1.edge.nextdns.io/dns-query
#    - https://ipv6-vultr-sel-1.edge.nextdns.io/dns-query
#    - https://ipv6-anexia-hkg-1.edge.nextdns.io/dns-query
#    - https://ipv6-vultr-sin-1.edge.nextdns.io/dns-query
#    - https://ipv6-starry-osa-1.edge.nextdns.io/dns-query
#    - https://ipv6-xtom-osa-1.edge.nextdns.io/dns-query
#    - https://ipv6-zepto-hkg-1.edge.nextdns.io/dns-query
#    - https://ipv6-greencloud-han-1.edge.nextdns.io/dns-query
#    - https://ipv6-dns1.nextdns.io/dns-query
#    - https://ipv6-dns2.nextdns.io/dns-query


##Edns
#    - quic://dns.nextdns.io:853
    - tls://dns.nextdns.io:853
    - https://dns.nextdns.io/dns-query

#    - 'quic://dns.nextdns.io:853#故障转移'
    - 'tls://dns.nextdns.io:853#故障转移'
    - 'https://dns.nextdns.io/dns-query#故障转移'
#    - https://103.246.218.132/dns-query
#    - https://37.252.243.39/dns-query


    ##Anycast Nextdns
#    - quic://anycast.dns.nextdns.io:853
#    - tls://anycast.dns.nextdns.io:853
#    - https://anycast.dns.nextdns.io/dns-query
#    - https://45.90.28.0/dns-query
#    - https://45.90.30.0/dns-query

#Quadrant DNS(No Filter/No log)
#    - tls://dns-tls.qis.io:853
#    - https://doh.qis.io/dns-query
#    - tls://12.159.2.159:853
#    - https://12.159.2.159/dns-query

#Mullvad VPN(No Filter/No log)
#    - tls://doh.mullvad.net:853
#    - https://doh.mullvad.net/dns-query
#    - tls://194.242.2.2:853
#    - https://194.242.2.2/dns-query
#    - tls://193.19.108.2:853
#    - https://193.19.108.2/dns-query

#Opendns(Filtering/loging)
#    - https://doh.opendns.com/dns-query


  fallback-filter:
    geoip: true
    geoip-code: CN
#    geosite:                         
    #【Meta专属】设定geosite某分类使用fallback返回结果
#      - gfw
#      - greatfire
#      - geolocation-!cn
    ipcidr:
     - 0.0.0.0/8
     - 10.0.0.0/8
     - 100.64.0.0/10
     - 127.0.0.0/8
     - 169.254.0.0/16
     - 172.16.0.0/12
     - 192.0.0.0/24
     - 192.0.2.0/24
     - 192.88.99.0/24
     - 192.168.0.0/16
     - 198.18.0.0/16
     - 198.51.100.0/24
     - 203.0.113.0/24
     - 224.0.0.0/4
     - 240.0.0.0/4
     - 255.255.255.255/32
     - ::1/128
     - fc00::/7
     - fe80::/10
#反诈 拦截
     - 39.102.194.95/32
     - 182.43.124.6/32
     - 101.35.177.86/32
    domain:
      - 'url.xincache.com'
    #google
#      - 'clients3.google.com'

      - '+.ampproject.org'
      - '+.appspot.com'
      - '+.blogger.com'
      - '+.google.com'
      - '+.google.cn'
      - '+.googleusercontent.com'
      - '+.ggpht.com'
      - '+.gmail.com'
      - '+.gvt0.com'
      - '+.gvt1.com'
      - '+.gvt2.com'
      - '+.gvt3.com'
      - '+.youtu.be'
      - '+.yt.be'
      - '+.ytimg.com'
      - '+.googlevideo.com'
      - '+.youtube.com'
#      - '+.xn--ngstr-lra8j.com'
#      - '+.xn--flw351e.com'
#      - '+.xn--9kr7l.com'
#      - '+.xn--ggle-55da.com'
#      - '+.xn--gogl-0nd52e.com'
#      - '+.xn--gogl-1nd42e.com'
#Google 定位
      - '+.googleapis.com'
      - '+.googleapis.cn'
      - '+.gstatic.com'
      - '+.gstatic.cn'
      - '+.services.googleapis.cn'
      - '+.services.googleapis.com'
      - '+.connectivitycheck.gstatic.cn'
      - '+.connectivitycheck.gstatic.com'

interface-name: ccmni0

ebpf:
  auto-redir:
    - ccmni0
    # - wlan0

tun:
  enable: true
  stack: gvisor
#  device-url: dev://net/tun
  dns-hijack:
    - any:53
#  auto-route: true 
#  auto-detect-interface: true



# Man-In-The-Middle attack
mitm:
  hosts: # use for others proxy type. E.g: TUN, socks
    - +.xxxx.cn
  rules: # rewrite rules


#    - '^https?://www\.example\.com/11 url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'

    - '^https?://xxx\.xxx\.xxx\.cn/akm-hsjc/self/getHSInfo(.*?) url response-body "errCode":"1001" response-body "errCode":"11"'




#    - '^https?://www\.example\.com/1 url reject' # The "reject" returns HTTP status code 404 with no content.
#    - '^https?://www\.example\.com/2 url reject-200' # The "reject-200" returns HTTP status code 200 with no content.
#    - '^https?://www\.example\.com/3 url reject-img' # The "reject-img" returns HTTP status code 200 with content of 1px png.
#    - '^https?://www\.example\.com/4 url reject-dict' # The "reject-dict" returns HTTP status code 200 with content of empty json object.
#    - '^https?://www\.example\.com/5 url reject-array' # The "reject-array" returns HTTP status code 200 with content of empty json array.
#    - '^https?://www\.example\.com/(6) url 302 https://www.example.com/new-$1'
#    - '^https?://www\.(example)\.com/7 url 307 https://www.$1.com/new-7'
#    - '^https?://www\.example\.com/8 url request-header (\r\n)User-Agent:.+(\r\n) request-header $1User-Agent: haha-wriohoh$2' # The "request-header" works for all the http headers not just one single header, so you can match two or more headers including CRLF in one regular expression.
#    - '^https?://www\.example\.com/9 url request-body "pos_2":\[.*\],"pos_3" request-body "pos_2":[{"xx": "xx"}],"pos_3"'
#    - '^https?://www\.example\.com/10 url response-header (\r\n)Tracecode:.+(\r\n) response-header $1Tracecode: 88888888888$2'
#    - '^https?://www\.example\.com/11 url response-body "errmsg":"ok" response-body "errmsg":"not-ok"'



proxy-providers:



proxy-groups:
  - name: 国外代理
    type: select
    use:
      - Mianliu
      - Cloudflare
#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    proxies:
      - 延迟测试
      - 故障转移
      - DIRECT
      - 负载均衡

  - name: 视频流媒体
    type: select
    use:
      - Mianliu
      - Cloudflare
#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    proxies:
#      - 延迟测试
#      - 故障转移
      - DIRECT
#      - 负载均衡

  - name: AD
    type: select
    use:
      - Mianliu
      - Cloudflare
#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    proxies:
      - DIRECT
      - REJECT
      - 延迟测试
      - 故障转移

  - name: 延迟测试
    type: url-test
    use:

#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    tolerance: 500
    # lazy: true
    url: http://clients3.google.com/generate_204
    interval: 300

  - name: 负载均衡
    type: load-balance
    use:

#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
#      - Openit
#      - FreeV2
    url: http://clients3.google.com/generate_204
    interval: 300
    # disable-udp: true
    strategy: consistent-hashing
    # consistent-hashing 同域名同连接
    # round-robin 随机连接

  - name: 故障转移
    type: fallback
    use:

#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    url: http://clients3.google.com/generate_204
    interval: 15

  - name: 远程桌面
    type: select
    use:
      - Mianliu
      - Cloudflare
#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    proxies:
      - 故障转移
      - 延迟测试
      - DIRECT
      
  - name: 游戏
    type: select
    use:
      - Mianliu
      - Cloudflare
#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    proxies:
      - DIRECT
      - 国外代理
      - 故障转移

  - name: 网易云音乐
    type: select
    use:
      - Netease
    proxies:
      - DIRECT
 


  - name: 国内直连
    type: select
    use:
      - Mianliu
      - Cloudflare
#      - Heroku
      - IEPL-1
      - IEPL-2
      - IPLC-1
      - IPLC-2
      - Node-1
      - Openit
      - FreeV2
    proxies:
      - DIRECT
      - 国外代理


rules:

#Local
 - DOMAIN-SUFFIX,local,DIRECT
 - DOMAIN-SUFFIX,localhost,DIRECT
 - DOMAIN-SUFFIX,ip6-localhost,DIRECT
 - DOMAIN-SUFFIX,ip6-loopback,DIRECT
 - IP-CIDR,0.0.0.0/8,DIRECT,no-resolve
 - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
 - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
 - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
 - IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
 - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
 - IP-CIDR,192.0.0.0/24,DIRECT,no-resolve
 - IP-CIDR,192.0.2.0/24,DIRECT,no-resolve
 - IP-CIDR,192.88.99.0/24,DIRECT,no-resolve
 - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
 - IP-CIDR,198.18.0.0/16,DIRECT,no-resolve
 - IP-CIDR,198.51.100.0/24,DIRECT,no-resolve
 - IP-CIDR,203.0.113.0/24,DIRECT,no-resolve
 - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
 - IP-CIDR,240.0.0.0/4,DIRECT,no-resolve
 - IP-CIDR,255.255.255.255/32,DIRECT,no-resolve
 - IP-CIDR6,::1/128,DIRECT,no-resolve
 - IP-CIDR6,fc00::/7,DIRECT,no-resolve
 - IP-CIDR6,fe80::/10,DIRECT,no-resolve


 - GEOIP,CN,国内直连
 - MATCH,国外代理
```

### Clash log

```shell
# cpfm cd /data/cpfm
# cpfm /data/cpfm/clash -d /data/cpfm/
03:51:00 INF > [Config] initial proxy provider name=Netease
03:51:00 INF > [Config] initial proxy provider name=Cloudflare
03:51:00 INF > [Config] initial proxy provider name=Node-1
03:51:00 INF > [Config] initial proxy provider name=Openit
03:51:00 INF > [Config] initial proxy provider name=Mianliu
03:51:00 INF > [Config] initial proxy provider name=IPLC-1
03:51:00 INF > [Config] initial proxy provider name=IEPL-2
03:51:00 INF > [Config] initial proxy provider name=FreeV2
03:51:00 INF > [Config] initial proxy provider name=IPLC-2
03:51:00 INF > [Config] initial proxy provider name=IEPL-1
03:51:00 INF > [Config] initial compatible provider name=AD
03:51:00 INF > [Config] initial compatible provider name=国内直连
03:51:00 INF > [Config] initial compatible provider name=远程桌面
03:51:00 INF > [Config] initial compatible provider name=国外代理
03:51:00 INF > [Config] initial compatible provider name=游戏
03:51:00 INF > [Config] initial compatible provider name=视频流媒体
03:51:00 INF > [Config] initial compatible provider name=网易云音乐
03:51:00 INF > [Config] initial script module successful
03:51:00 INF > [API] listening addr=[::]:9090
03:51:00 INF > [DNS] dns server listening addr=[::]:53
03:51:00 INF > [Config] interface name=ccmni0
03:51:00 INF > [Config] tls sniffing=false
03:51:00 INF > [Inbound] Mixed(http+socks) proxy listening addr=[::]:7890
03:51:01 INF > [Inbound] MITM proxy listening addr=[::]:7894
03:51:01 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:02 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:03 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:04 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:05 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:06 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:07 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:08 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:09 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:10 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:11 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:12 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:13 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:14 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:15 INF > [TUN] Start tun retrying lookup default interface after failure because system just booted
03:51:16 ERR > [Inbound] TUN server start failed error=setting interface address and routing failed: default interface not found
03:51:16 ERR > [Inbound] Attached tc ebpf program failed error=lookup network iface "": Link not found
```

### Description

运行报错 [TUN] Start tun retrying lookup default interface after failure because system just booted
